export const DUMMY_PROJECTS = [{
    id: "p1",
    name: "Brand Identity Redesign",
    category: "Design",
    date: "1/24/2024",
    value: 35000,
    status: "active",
},
{
    id: "p2",
    name: "Content Marketing Plan",
    category: "Marketing",
    date: "1/29/2024",
    value: 15000,
    status: "active",
},
{
    id: "p3",
    name: "Customer Support System",
    category: "Technology",
    date: "1/19/2024",
    value: 45000,
    status: "completed",
},
{
    id: "p4",
    name: "Employee Training Program",
    category: "HR",
    date: "1/21/2024",
    value: 22000,
    status: "pending",
},
{
    id: "p5",
    name: "Financial Planning Review",
    category: "Finance",
    date: "1/4/2024",
    value: 55000,
    status: "pending",
},
{
    id: "p6",
    name: "Mobile App Development",
    category: "Technology",
    date: "1/17/2024",
    value: 75000,
    status: "active",
},
{
    id: "p7",
    name: "Product Launch Campaign",
    category: "Marketing",
    date: "1/14/2024",
    value: 25000,
    status: "active",
},
{
    id: "p8",
    name: "Q4 Sales Analysis",
    category: "Sales",
    date: "1/9/2024",
    value: 12000,
    status: "pending",
},
{
    id: "p9",
    name: "Social Media Strategy",
    category: "Marketing",
    date: "1/11/2024",
    value: 18000,
    status: "completed",
},
{
    id: "p10",
    name: "Website Performance Audit",
    category: "Technology",
    date: "1/7/2024",
    value: 8000,
    status: "completed",
}]